# use value of env var if set, otherwise use 'default' 
STAGE?=default

check:
	@echo "all checks successful."

# build target has 'check' as dependency
build: check
	@echo "build done on '$(STAGE)'."
